name: Build docker images

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and upload docker image
    runs-on: ubuntu-latest
    steps:
      - run: sudo rm -rf /opt&
      - uses: actions/checkout@v4
      - uses: paolino/dev-assets/setup-nix@v0.0.1
        with:
          cachix-auth-token: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build oracle docker image
        run: nix build .#moog-oracle-docker-image -o moog-oracle-image
      - name: Smoke test oracle docker image
        run: |
          IMAGE=$(docker load < moog-oracle-image | grep "Loaded image:" | awk '{print $3}')
          docker run --rm "$IMAGE" --help
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: moog-oracle-image
          path: ./moog-oracle-image
      - name: Build agent docker image
        run: nix build .#moog-agent-docker-image -o moog-agent-image
      - name: Smoke test agent docker image
        run: |
          IMAGE=$(docker load < moog-agent-image | grep "Loaded image:" | awk '{print $3}')
          docker run --rm "$IMAGE" --help
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: moog-agent-image
          path: ./moog-agent-image
  build-aarch64:
    name: Build and upload ARM64 docker images
    runs-on: ubuntu-24.04-arm
    steps:
      - run: sudo rm -rf /opt&
      - uses: actions/checkout@v4
      - uses: paolino/dev-assets/setup-nix@v0.0.1
        with:
          cachix-auth-token: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build oracle docker image
        run: nix build .#moog-oracle-docker-image -o moog-oracle-image-aarch64
      - name: Smoke test oracle docker image
        run: |
          IMAGE=$(docker load < moog-oracle-image-aarch64 | grep "Loaded image:" | awk '{print $3}')
          docker run --rm "$IMAGE" --help
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: moog-oracle-image-aarch64
          path: ./moog-oracle-image-aarch64
      - name: Build agent docker image
        run: nix build .#moog-agent-docker-image -o moog-agent-image-aarch64
      - name: Smoke test agent docker image
        run: |
          IMAGE=$(docker load < moog-agent-image-aarch64 | grep "Loaded image:" | awk '{print $3}')
          docker run --rm "$IMAGE" --help
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: moog-agent-image-aarch64
          path: ./moog-agent-image-aarch64
