name: Build tarballs

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  linux-tarball:
    name: Build and upload linux tarball
    runs-on: ubuntu-latest
    steps:
      - run: sudo rm -rf /opt&
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://cache.iog.io https://cache.nixos.org/
            accept-flake-config = true
      - uses: cachix/cachix-action@v15
        with:
          name: paolino
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build oracle docker image
        run: nix --quiet build -L .#linux64.tarball -o linux-tarball
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-tarball
          path: ./linux-tarball
  macos-tarball:
    name: Build and upload macOS tarball
    runs-on: macos-latest
    steps:
      - run: sudo rm -rf /opt&
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://cache.iog.io https://cache.nixos.org/
            accept-flake-config = true
      - uses: cachix/cachix-action@v15
        with:
          name: paolino
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build macOS tarball
        run: nix --quiet build .#darwin64.tarball -o darwin-tarball
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: darwin-tarball
          path: ./darwin-tarball